services:
  web:
    build: ./web
    ports:
      - "80:80"
    volumes:
      - ./web/myhtmlcode:/usr/share/nginx/html
      - ./web/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - webnet

  app:
    build: ./app
    volumes:
      - ./app/myphpcode:/usr/share/nginx/html
    networks:
      - webnet
      - dbnet
    ports:
      - "9000"

  db:
    build: ./db
    ports:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: Pass@123
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - databuckup:/var/lib/mysql/
    networks:
      - dbnet

networks:
  webnet:
    driver: bridge
  dbnet:
    driver: bridge

volumes:
  databuckup:
